// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sdstable
NumericVector sdstable(Eigen::VectorXd x, double alpha, double beta, int log_flag, double tol, double zeta_tol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_sdstable(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP log_flagSEXP, SEXP tolSEXP, SEXP zeta_tolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type log_flag(log_flagSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_tol(zeta_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdstable(x, alpha, beta, log_flag, tol, zeta_tol, subdivisions, verbose));
    return __result;
END_RCPP
}
// sdstable_quick
NumericVector sdstable_quick(Eigen::VectorXd x, double alpha, double beta, int log_flag, double tol, double zeta_tol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_sdstable_quick(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP log_flagSEXP, SEXP tolSEXP, SEXP zeta_tolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type log_flag(log_flagSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_tol(zeta_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdstable_quick(x, alpha, beta, log_flag, tol, zeta_tol, subdivisions, verbose));
    return __result;
END_RCPP
}
// spstable
NumericVector spstable(Eigen::VectorXd z, double alpha, double beta, int lower_tail, int log_p, double dbltol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_spstable(SEXP zSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP, SEXP dbltolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< int >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< double >::type dbltol(dbltolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(spstable(z, alpha, beta, lower_tail, log_p, dbltol, subdivisions, verbose));
    return __result;
END_RCPP
}
// sqstable
NumericVector sqstable(Eigen::VectorXd p, double alpha, double beta, int lower_tail, int log_p, double dbltol, double integ_tol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_sqstable(SEXP pSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP, SEXP dbltolSEXP, SEXP integ_tolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< int >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< double >::type dbltol(dbltolSEXP);
    Rcpp::traits::input_parameter< double >::type integ_tol(integ_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sqstable(p, alpha, beta, lower_tail, log_p, dbltol, integ_tol, subdivisions, verbose));
    return __result;
END_RCPP
}
// ddx_sdstable
NumericVector ddx_sdstable(Eigen::VectorXd x, double alpha, double beta, double tol, double zeta_tol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_ddx_sdstable(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP zeta_tolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_tol(zeta_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(ddx_sdstable(x, alpha, beta, tol, zeta_tol, subdivisions, verbose));
    return __result;
END_RCPP
}
// srstable
NumericVector srstable(double alpha, double beta, Eigen::VectorXd u1, Eigen::VectorXd u2);
RcppExport SEXP stablecpp_srstable(SEXP alphaSEXP, SEXP betaSEXP, SEXP u1SEXP, SEXP u2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type u2(u2SEXP);
    __result = Rcpp::wrap(srstable(alpha, beta, u1, u2));
    return __result;
END_RCPP
}
// sdstableMode
double sdstableMode(double alpha, double beta, double dbltol, double tol, double zeta_tol, int subdivisions, int verbose);
RcppExport SEXP stablecpp_sdstableMode(SEXP alphaSEXP, SEXP betaSEXP, SEXP dbltolSEXP, SEXP tolSEXP, SEXP zeta_tolSEXP, SEXP subdivisionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type dbltol(dbltolSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_tol(zeta_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdstableMode(alpha, beta, dbltol, tol, zeta_tol, subdivisions, verbose));
    return __result;
END_RCPP
}
// stable_fit_cpp
DataFrame stable_fit_cpp(Eigen::VectorXd y, std::string type, bool quick);
RcppExport SEXP stablecpp_stable_fit_cpp(SEXP ySEXP, SEXP typeSEXP, SEXP quickSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type quick(quickSEXP);
    __result = Rcpp::wrap(stable_fit_cpp(y, type, quick));
    return __result;
END_RCPP
}
