# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

guess_test <- function(p, alpha, beta, lower_tail, log_p) {
    .Call('stablecpp_guess_test', PACKAGE = 'stablecpp', p, alpha, beta, lower_tail, log_p)
}

q_guess <- function(p, alpha, beta, lower_tail, log_p) {
    .Call('stablecpp_q_guess', PACKAGE = 'stablecpp', p, alpha, beta, lower_tail, log_p)
}

test_g <- function(th, x, alpha, beta) {
    .Call('stablecpp_test_g', PACKAGE = 'stablecpp', th, x, alpha, beta)
}

test_sin <- function(x) {
    .Call('stablecpp_test_sin', PACKAGE = 'stablecpp', x)
}

sdstable <- function(x, alpha, beta, log_flag, tol, zeta_tol, subdivisions, verbose) {
    .Call('stablecpp_sdstable', PACKAGE = 'stablecpp', x, alpha, beta, log_flag, tol, zeta_tol, subdivisions, verbose)
}

spstable <- function(z, alpha, beta, lower_tail, log_p, dbltol, subdivisions, verbose) {
    .Call('stablecpp_spstable', PACKAGE = 'stablecpp', z, alpha, beta, lower_tail, log_p, dbltol, subdivisions, verbose)
}

sqstable <- function(p, alpha, beta, lower_tail, log_p, dbltol, integ_tol, subdivisions, verbose) {
    .Call('stablecpp_sqstable', PACKAGE = 'stablecpp', p, alpha, beta, lower_tail, log_p, dbltol, integ_tol, subdivisions, verbose)
}

ddx_sdstable <- function(x, alpha, beta, tol, zeta_tol, subdivisions, verbose) {
    .Call('stablecpp_ddx_sdstable', PACKAGE = 'stablecpp', x, alpha, beta, tol, zeta_tol, subdivisions, verbose)
}

sdstableMode <- function(alpha, beta, beta_max, dbltol, verbose) {
    .Call('stablecpp_sdstableMode', PACKAGE = 'stablecpp', alpha, beta, beta_max, dbltol, verbose)
}

cubic_spline <- function(x, x_knots, y_knots, isclamped, deriv) {
    .Call('stablecpp_cubic_spline', PACKAGE = 'stablecpp', x, x_knots, y_knots, isclamped, deriv)
}

sdstable_quick <- function(x, alpha, beta, tol, zeta_tol, subdivisions, verbose) {
    .Call('stablecpp_sdstable_quick', PACKAGE = 'stablecpp', x, alpha, beta, tol, zeta_tol, subdivisions, verbose)
}

